// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: startX.proto

#include "startX.pb.h"
#include "startX.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace Xproject {

static const char* StartX_method_names[] = {
  "/Xproject.StartX/GetCoreStatus",
};

std::unique_ptr< StartX::Stub> StartX::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StartX::Stub> stub(new StartX::Stub(channel));
  return stub;
}

StartX::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetCoreStatus_(StartX_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StartX::Stub::GetCoreStatus(::grpc::ClientContext* context, const ::Xproject::CoreStatusRequest& request, ::Xproject::CoreStatusReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetCoreStatus_, context, request, response);
}

void StartX::Stub::experimental_async::GetCoreStatus(::grpc::ClientContext* context, const ::Xproject::CoreStatusRequest* request, ::Xproject::CoreStatusReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetCoreStatus_, context, request, response, std::move(f));
}

void StartX::Stub::experimental_async::GetCoreStatus(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Xproject::CoreStatusReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetCoreStatus_, context, request, response, std::move(f));
}

void StartX::Stub::experimental_async::GetCoreStatus(::grpc::ClientContext* context, const ::Xproject::CoreStatusRequest* request, ::Xproject::CoreStatusReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetCoreStatus_, context, request, response, reactor);
}

void StartX::Stub::experimental_async::GetCoreStatus(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Xproject::CoreStatusReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetCoreStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Xproject::CoreStatusReply>* StartX::Stub::AsyncGetCoreStatusRaw(::grpc::ClientContext* context, const ::Xproject::CoreStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Xproject::CoreStatusReply>::Create(channel_.get(), cq, rpcmethod_GetCoreStatus_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Xproject::CoreStatusReply>* StartX::Stub::PrepareAsyncGetCoreStatusRaw(::grpc::ClientContext* context, const ::Xproject::CoreStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Xproject::CoreStatusReply>::Create(channel_.get(), cq, rpcmethod_GetCoreStatus_, context, request, false);
}

StartX::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StartX_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StartX::Service, ::Xproject::CoreStatusRequest, ::Xproject::CoreStatusReply>(
          std::mem_fn(&StartX::Service::GetCoreStatus), this)));
}

StartX::Service::~Service() {
}

::grpc::Status StartX::Service::GetCoreStatus(::grpc::ServerContext* context, const ::Xproject::CoreStatusRequest* request, ::Xproject::CoreStatusReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Xproject

