// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_glass.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_grpc_5fglass_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_grpc_5fglass_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "grpc_basicParameters.pb.h"
#include "grpc_checkResult.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_grpc_5fglass_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_grpc_5fglass_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_grpc_5fglass_2eproto;
namespace Xproject {
class GlassBookReply;
class GlassBookReplyDefaultTypeInternal;
extern GlassBookReplyDefaultTypeInternal _GlassBookReply_default_instance_;
class GlassCalReply;
class GlassCalReplyDefaultTypeInternal;
extern GlassCalReplyDefaultTypeInternal _GlassCalReply_default_instance_;
class GlassRequest;
class GlassRequestDefaultTypeInternal;
extern GlassRequestDefaultTypeInternal _GlassRequest_default_instance_;
}  // namespace Xproject
PROTOBUF_NAMESPACE_OPEN
template<> ::Xproject::GlassBookReply* Arena::CreateMaybeMessage<::Xproject::GlassBookReply>(Arena*);
template<> ::Xproject::GlassCalReply* Arena::CreateMaybeMessage<::Xproject::GlassCalReply>(Arena*);
template<> ::Xproject::GlassRequest* Arena::CreateMaybeMessage<::Xproject::GlassRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Xproject {

enum GlassRequest_GlassMaterial : int {
  GlassRequest_GlassMaterial_FLAT = 0,
  GlassRequest_GlassMaterial_TEMPERED = 1,
  GlassRequest_GlassMaterial_GlassRequest_GlassMaterial_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  GlassRequest_GlassMaterial_GlassRequest_GlassMaterial_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool GlassRequest_GlassMaterial_IsValid(int value);
constexpr GlassRequest_GlassMaterial GlassRequest_GlassMaterial_GlassMaterial_MIN = GlassRequest_GlassMaterial_FLAT;
constexpr GlassRequest_GlassMaterial GlassRequest_GlassMaterial_GlassMaterial_MAX = GlassRequest_GlassMaterial_TEMPERED;
constexpr int GlassRequest_GlassMaterial_GlassMaterial_ARRAYSIZE = GlassRequest_GlassMaterial_GlassMaterial_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GlassRequest_GlassMaterial_descriptor();
template<typename T>
inline const std::string& GlassRequest_GlassMaterial_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GlassRequest_GlassMaterial>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GlassRequest_GlassMaterial_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GlassRequest_GlassMaterial_descriptor(), enum_t_value);
}
inline bool GlassRequest_GlassMaterial_Parse(
    const std::string& name, GlassRequest_GlassMaterial* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GlassRequest_GlassMaterial>(
    GlassRequest_GlassMaterial_descriptor(), name, value);
}
enum grpc_GlassType : int {
  ONE = 0,
  HOLLOW = 1,
  LAMINATE = 2,
  HOLLOW_AND_LAMINATE = 3,
  DOUBLEHOLLOW = 4,
  DOUBLELAMINATE_AND_HOLLOW = 5,
  grpc_GlassType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  grpc_GlassType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool grpc_GlassType_IsValid(int value);
constexpr grpc_GlassType grpc_GlassType_MIN = ONE;
constexpr grpc_GlassType grpc_GlassType_MAX = DOUBLELAMINATE_AND_HOLLOW;
constexpr int grpc_GlassType_ARRAYSIZE = grpc_GlassType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* grpc_GlassType_descriptor();
template<typename T>
inline const std::string& grpc_GlassType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, grpc_GlassType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function grpc_GlassType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    grpc_GlassType_descriptor(), enum_t_value);
}
inline bool grpc_GlassType_Parse(
    const std::string& name, grpc_GlassType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<grpc_GlassType>(
    grpc_GlassType_descriptor(), name, value);
}
enum grpc_eOneGlassPanelResultType : int {
  STRENGTH = 0,
  DEFLECTION = 1,
  grpc_eOneGlassPanelResultType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  grpc_eOneGlassPanelResultType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool grpc_eOneGlassPanelResultType_IsValid(int value);
constexpr grpc_eOneGlassPanelResultType grpc_eOneGlassPanelResultType_MIN = STRENGTH;
constexpr grpc_eOneGlassPanelResultType grpc_eOneGlassPanelResultType_MAX = DEFLECTION;
constexpr int grpc_eOneGlassPanelResultType_ARRAYSIZE = grpc_eOneGlassPanelResultType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* grpc_eOneGlassPanelResultType_descriptor();
template<typename T>
inline const std::string& grpc_eOneGlassPanelResultType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, grpc_eOneGlassPanelResultType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function grpc_eOneGlassPanelResultType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    grpc_eOneGlassPanelResultType_descriptor(), enum_t_value);
}
inline bool grpc_eOneGlassPanelResultType_Parse(
    const std::string& name, grpc_eOneGlassPanelResultType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<grpc_eOneGlassPanelResultType>(
    grpc_eOneGlassPanelResultType_descriptor(), name, value);
}
// ===================================================================

class GlassRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Xproject.GlassRequest) */ {
 public:
  GlassRequest();
  virtual ~GlassRequest();

  GlassRequest(const GlassRequest& from);
  GlassRequest(GlassRequest&& from) noexcept
    : GlassRequest() {
    *this = ::std::move(from);
  }

  inline GlassRequest& operator=(const GlassRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GlassRequest& operator=(GlassRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GlassRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GlassRequest* internal_default_instance() {
    return reinterpret_cast<const GlassRequest*>(
               &_GlassRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GlassRequest& a, GlassRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GlassRequest* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GlassRequest* New() const final {
    return CreateMaybeMessage<GlassRequest>(nullptr);
  }

  GlassRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GlassRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GlassRequest& from);
  void MergeFrom(const GlassRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GlassRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Xproject.GlassRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_grpc_5fglass_2eproto);
    return ::descriptor_table_grpc_5fglass_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef GlassRequest_GlassMaterial GlassMaterial;
  static constexpr GlassMaterial FLAT =
    GlassRequest_GlassMaterial_FLAT;
  static constexpr GlassMaterial TEMPERED =
    GlassRequest_GlassMaterial_TEMPERED;
  static inline bool GlassMaterial_IsValid(int value) {
    return GlassRequest_GlassMaterial_IsValid(value);
  }
  static constexpr GlassMaterial GlassMaterial_MIN =
    GlassRequest_GlassMaterial_GlassMaterial_MIN;
  static constexpr GlassMaterial GlassMaterial_MAX =
    GlassRequest_GlassMaterial_GlassMaterial_MAX;
  static constexpr int GlassMaterial_ARRAYSIZE =
    GlassRequest_GlassMaterial_GlassMaterial_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  GlassMaterial_descriptor() {
    return GlassRequest_GlassMaterial_descriptor();
  }
  template<typename T>
  static inline const std::string& GlassMaterial_Name(T enum_t_value) {
    static_assert(::std::is_same<T, GlassMaterial>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function GlassMaterial_Name.");
    return GlassRequest_GlassMaterial_Name(enum_t_value);
  }
  static inline bool GlassMaterial_Parse(const std::string& name,
      GlassMaterial* value) {
    return GlassRequest_GlassMaterial_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kThicknessFieldNumber = 5,
    kParametersFieldNumber = 1,
    kWidthFieldNumber = 2,
    kHeightFieldNumber = 3,
    kMatFieldNumber = 4,
    kTypeFieldNumber = 6,
  };
  // repeated double thickness = 5;
  int thickness_size() const;
  private:
  int _internal_thickness_size() const;
  public:
  void clear_thickness();
  private:
  double _internal_thickness(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_thickness() const;
  void _internal_add_thickness(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_thickness();
  public:
  double thickness(int index) const;
  void set_thickness(int index, double value);
  void add_thickness(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      thickness() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_thickness();

  // .Xproject.grpc_BasicParameters parameters = 1;
  bool has_parameters() const;
  private:
  bool _internal_has_parameters() const;
  public:
  void clear_parameters();
  const ::Xproject::grpc_BasicParameters& parameters() const;
  ::Xproject::grpc_BasicParameters* release_parameters();
  ::Xproject::grpc_BasicParameters* mutable_parameters();
  void set_allocated_parameters(::Xproject::grpc_BasicParameters* parameters);
  private:
  const ::Xproject::grpc_BasicParameters& _internal_parameters() const;
  ::Xproject::grpc_BasicParameters* _internal_mutable_parameters();
  public:

  // double width = 2;
  void clear_width();
  double width() const;
  void set_width(double value);
  private:
  double _internal_width() const;
  void _internal_set_width(double value);
  public:

  // double height = 3;
  void clear_height();
  double height() const;
  void set_height(double value);
  private:
  double _internal_height() const;
  void _internal_set_height(double value);
  public:

  // .Xproject.GlassRequest.GlassMaterial mat = 4;
  void clear_mat();
  ::Xproject::GlassRequest_GlassMaterial mat() const;
  void set_mat(::Xproject::GlassRequest_GlassMaterial value);
  private:
  ::Xproject::GlassRequest_GlassMaterial _internal_mat() const;
  void _internal_set_mat(::Xproject::GlassRequest_GlassMaterial value);
  public:

  // .Xproject.grpc_GlassType type = 6;
  void clear_type();
  ::Xproject::grpc_GlassType type() const;
  void set_type(::Xproject::grpc_GlassType value);
  private:
  ::Xproject::grpc_GlassType _internal_type() const;
  void _internal_set_type(::Xproject::grpc_GlassType value);
  public:

  // @@protoc_insertion_point(class_scope:Xproject.GlassRequest)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > thickness_;
  mutable std::atomic<int> _thickness_cached_byte_size_;
  ::Xproject::grpc_BasicParameters* parameters_;
  double width_;
  double height_;
  int mat_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_grpc_5fglass_2eproto;
};
// -------------------------------------------------------------------

class GlassCalReply :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Xproject.GlassCalReply) */ {
 public:
  GlassCalReply();
  virtual ~GlassCalReply();

  GlassCalReply(const GlassCalReply& from);
  GlassCalReply(GlassCalReply&& from) noexcept
    : GlassCalReply() {
    *this = ::std::move(from);
  }

  inline GlassCalReply& operator=(const GlassCalReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline GlassCalReply& operator=(GlassCalReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GlassCalReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GlassCalReply* internal_default_instance() {
    return reinterpret_cast<const GlassCalReply*>(
               &_GlassCalReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GlassCalReply& a, GlassCalReply& b) {
    a.Swap(&b);
  }
  inline void Swap(GlassCalReply* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GlassCalReply* New() const final {
    return CreateMaybeMessage<GlassCalReply>(nullptr);
  }

  GlassCalReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GlassCalReply>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GlassCalReply& from);
  void MergeFrom(const GlassCalReply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GlassCalReply* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Xproject.GlassCalReply";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_grpc_5fglass_2eproto);
    return ::descriptor_table_grpc_5fglass_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDescriptionFieldNumber = 3,
    kCalResultsFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // string description = 3;
  void clear_description();
  const std::string& description() const;
  void set_description(const std::string& value);
  void set_description(std::string&& value);
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  std::string* mutable_description();
  std::string* release_description();
  void set_allocated_description(std::string* description);
  private:
  const std::string& _internal_description() const;
  void _internal_set_description(const std::string& value);
  std::string* _internal_mutable_description();
  public:

  // .Xproject.grpc_CommonCalResult calResults = 1;
  bool has_calresults() const;
  private:
  bool _internal_has_calresults() const;
  public:
  void clear_calresults();
  const ::Xproject::grpc_CommonCalResult& calresults() const;
  ::Xproject::grpc_CommonCalResult* release_calresults();
  ::Xproject::grpc_CommonCalResult* mutable_calresults();
  void set_allocated_calresults(::Xproject::grpc_CommonCalResult* calresults);
  private:
  const ::Xproject::grpc_CommonCalResult& _internal_calresults() const;
  ::Xproject::grpc_CommonCalResult* _internal_mutable_calresults();
  public:

  // .Xproject.grpc_GlassType type = 2;
  void clear_type();
  ::Xproject::grpc_GlassType type() const;
  void set_type(::Xproject::grpc_GlassType value);
  private:
  ::Xproject::grpc_GlassType _internal_type() const;
  void _internal_set_type(::Xproject::grpc_GlassType value);
  public:

  // @@protoc_insertion_point(class_scope:Xproject.GlassCalReply)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
  ::Xproject::grpc_CommonCalResult* calresults_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_grpc_5fglass_2eproto;
};
// -------------------------------------------------------------------

class GlassBookReply :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Xproject.GlassBookReply) */ {
 public:
  GlassBookReply();
  virtual ~GlassBookReply();

  GlassBookReply(const GlassBookReply& from);
  GlassBookReply(GlassBookReply&& from) noexcept
    : GlassBookReply() {
    *this = ::std::move(from);
  }

  inline GlassBookReply& operator=(const GlassBookReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline GlassBookReply& operator=(GlassBookReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GlassBookReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GlassBookReply* internal_default_instance() {
    return reinterpret_cast<const GlassBookReply*>(
               &_GlassBookReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GlassBookReply& a, GlassBookReply& b) {
    a.Swap(&b);
  }
  inline void Swap(GlassBookReply* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GlassBookReply* New() const final {
    return CreateMaybeMessage<GlassBookReply>(nullptr);
  }

  GlassBookReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GlassBookReply>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GlassBookReply& from);
  void MergeFrom(const GlassBookReply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GlassBookReply* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Xproject.GlassBookReply";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_grpc_5fglass_2eproto);
    return ::descriptor_table_grpc_5fglass_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
  };
  // string result = 1;
  void clear_result();
  const std::string& result() const;
  void set_result(const std::string& value);
  void set_result(std::string&& value);
  void set_result(const char* value);
  void set_result(const char* value, size_t size);
  std::string* mutable_result();
  std::string* release_result();
  void set_allocated_result(std::string* result);
  private:
  const std::string& _internal_result() const;
  void _internal_set_result(const std::string& value);
  std::string* _internal_mutable_result();
  public:

  // @@protoc_insertion_point(class_scope:Xproject.GlassBookReply)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr result_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_grpc_5fglass_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GlassRequest

// .Xproject.grpc_BasicParameters parameters = 1;
inline bool GlassRequest::_internal_has_parameters() const {
  return this != internal_default_instance() && parameters_ != nullptr;
}
inline bool GlassRequest::has_parameters() const {
  return _internal_has_parameters();
}
inline const ::Xproject::grpc_BasicParameters& GlassRequest::_internal_parameters() const {
  const ::Xproject::grpc_BasicParameters* p = parameters_;
  return p != nullptr ? *p : *reinterpret_cast<const ::Xproject::grpc_BasicParameters*>(
      &::Xproject::_grpc_BasicParameters_default_instance_);
}
inline const ::Xproject::grpc_BasicParameters& GlassRequest::parameters() const {
  // @@protoc_insertion_point(field_get:Xproject.GlassRequest.parameters)
  return _internal_parameters();
}
inline ::Xproject::grpc_BasicParameters* GlassRequest::release_parameters() {
  // @@protoc_insertion_point(field_release:Xproject.GlassRequest.parameters)
  
  ::Xproject::grpc_BasicParameters* temp = parameters_;
  parameters_ = nullptr;
  return temp;
}
inline ::Xproject::grpc_BasicParameters* GlassRequest::_internal_mutable_parameters() {
  
  if (parameters_ == nullptr) {
    auto* p = CreateMaybeMessage<::Xproject::grpc_BasicParameters>(GetArenaNoVirtual());
    parameters_ = p;
  }
  return parameters_;
}
inline ::Xproject::grpc_BasicParameters* GlassRequest::mutable_parameters() {
  // @@protoc_insertion_point(field_mutable:Xproject.GlassRequest.parameters)
  return _internal_mutable_parameters();
}
inline void GlassRequest::set_allocated_parameters(::Xproject::grpc_BasicParameters* parameters) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(parameters_);
  }
  if (parameters) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      parameters = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, parameters, submessage_arena);
    }
    
  } else {
    
  }
  parameters_ = parameters;
  // @@protoc_insertion_point(field_set_allocated:Xproject.GlassRequest.parameters)
}

// double width = 2;
inline void GlassRequest::clear_width() {
  width_ = 0;
}
inline double GlassRequest::_internal_width() const {
  return width_;
}
inline double GlassRequest::width() const {
  // @@protoc_insertion_point(field_get:Xproject.GlassRequest.width)
  return _internal_width();
}
inline void GlassRequest::_internal_set_width(double value) {
  
  width_ = value;
}
inline void GlassRequest::set_width(double value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:Xproject.GlassRequest.width)
}

// double height = 3;
inline void GlassRequest::clear_height() {
  height_ = 0;
}
inline double GlassRequest::_internal_height() const {
  return height_;
}
inline double GlassRequest::height() const {
  // @@protoc_insertion_point(field_get:Xproject.GlassRequest.height)
  return _internal_height();
}
inline void GlassRequest::_internal_set_height(double value) {
  
  height_ = value;
}
inline void GlassRequest::set_height(double value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:Xproject.GlassRequest.height)
}

// .Xproject.GlassRequest.GlassMaterial mat = 4;
inline void GlassRequest::clear_mat() {
  mat_ = 0;
}
inline ::Xproject::GlassRequest_GlassMaterial GlassRequest::_internal_mat() const {
  return static_cast< ::Xproject::GlassRequest_GlassMaterial >(mat_);
}
inline ::Xproject::GlassRequest_GlassMaterial GlassRequest::mat() const {
  // @@protoc_insertion_point(field_get:Xproject.GlassRequest.mat)
  return _internal_mat();
}
inline void GlassRequest::_internal_set_mat(::Xproject::GlassRequest_GlassMaterial value) {
  
  mat_ = value;
}
inline void GlassRequest::set_mat(::Xproject::GlassRequest_GlassMaterial value) {
  _internal_set_mat(value);
  // @@protoc_insertion_point(field_set:Xproject.GlassRequest.mat)
}

// repeated double thickness = 5;
inline int GlassRequest::_internal_thickness_size() const {
  return thickness_.size();
}
inline int GlassRequest::thickness_size() const {
  return _internal_thickness_size();
}
inline void GlassRequest::clear_thickness() {
  thickness_.Clear();
}
inline double GlassRequest::_internal_thickness(int index) const {
  return thickness_.Get(index);
}
inline double GlassRequest::thickness(int index) const {
  // @@protoc_insertion_point(field_get:Xproject.GlassRequest.thickness)
  return _internal_thickness(index);
}
inline void GlassRequest::set_thickness(int index, double value) {
  thickness_.Set(index, value);
  // @@protoc_insertion_point(field_set:Xproject.GlassRequest.thickness)
}
inline void GlassRequest::_internal_add_thickness(double value) {
  thickness_.Add(value);
}
inline void GlassRequest::add_thickness(double value) {
  _internal_add_thickness(value);
  // @@protoc_insertion_point(field_add:Xproject.GlassRequest.thickness)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
GlassRequest::_internal_thickness() const {
  return thickness_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
GlassRequest::thickness() const {
  // @@protoc_insertion_point(field_list:Xproject.GlassRequest.thickness)
  return _internal_thickness();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
GlassRequest::_internal_mutable_thickness() {
  return &thickness_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
GlassRequest::mutable_thickness() {
  // @@protoc_insertion_point(field_mutable_list:Xproject.GlassRequest.thickness)
  return _internal_mutable_thickness();
}

// .Xproject.grpc_GlassType type = 6;
inline void GlassRequest::clear_type() {
  type_ = 0;
}
inline ::Xproject::grpc_GlassType GlassRequest::_internal_type() const {
  return static_cast< ::Xproject::grpc_GlassType >(type_);
}
inline ::Xproject::grpc_GlassType GlassRequest::type() const {
  // @@protoc_insertion_point(field_get:Xproject.GlassRequest.type)
  return _internal_type();
}
inline void GlassRequest::_internal_set_type(::Xproject::grpc_GlassType value) {
  
  type_ = value;
}
inline void GlassRequest::set_type(::Xproject::grpc_GlassType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:Xproject.GlassRequest.type)
}

// -------------------------------------------------------------------

// GlassCalReply

// .Xproject.grpc_CommonCalResult calResults = 1;
inline bool GlassCalReply::_internal_has_calresults() const {
  return this != internal_default_instance() && calresults_ != nullptr;
}
inline bool GlassCalReply::has_calresults() const {
  return _internal_has_calresults();
}
inline const ::Xproject::grpc_CommonCalResult& GlassCalReply::_internal_calresults() const {
  const ::Xproject::grpc_CommonCalResult* p = calresults_;
  return p != nullptr ? *p : *reinterpret_cast<const ::Xproject::grpc_CommonCalResult*>(
      &::Xproject::_grpc_CommonCalResult_default_instance_);
}
inline const ::Xproject::grpc_CommonCalResult& GlassCalReply::calresults() const {
  // @@protoc_insertion_point(field_get:Xproject.GlassCalReply.calResults)
  return _internal_calresults();
}
inline ::Xproject::grpc_CommonCalResult* GlassCalReply::release_calresults() {
  // @@protoc_insertion_point(field_release:Xproject.GlassCalReply.calResults)
  
  ::Xproject::grpc_CommonCalResult* temp = calresults_;
  calresults_ = nullptr;
  return temp;
}
inline ::Xproject::grpc_CommonCalResult* GlassCalReply::_internal_mutable_calresults() {
  
  if (calresults_ == nullptr) {
    auto* p = CreateMaybeMessage<::Xproject::grpc_CommonCalResult>(GetArenaNoVirtual());
    calresults_ = p;
  }
  return calresults_;
}
inline ::Xproject::grpc_CommonCalResult* GlassCalReply::mutable_calresults() {
  // @@protoc_insertion_point(field_mutable:Xproject.GlassCalReply.calResults)
  return _internal_mutable_calresults();
}
inline void GlassCalReply::set_allocated_calresults(::Xproject::grpc_CommonCalResult* calresults) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(calresults_);
  }
  if (calresults) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      calresults = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, calresults, submessage_arena);
    }
    
  } else {
    
  }
  calresults_ = calresults;
  // @@protoc_insertion_point(field_set_allocated:Xproject.GlassCalReply.calResults)
}

// .Xproject.grpc_GlassType type = 2;
inline void GlassCalReply::clear_type() {
  type_ = 0;
}
inline ::Xproject::grpc_GlassType GlassCalReply::_internal_type() const {
  return static_cast< ::Xproject::grpc_GlassType >(type_);
}
inline ::Xproject::grpc_GlassType GlassCalReply::type() const {
  // @@protoc_insertion_point(field_get:Xproject.GlassCalReply.type)
  return _internal_type();
}
inline void GlassCalReply::_internal_set_type(::Xproject::grpc_GlassType value) {
  
  type_ = value;
}
inline void GlassCalReply::set_type(::Xproject::grpc_GlassType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:Xproject.GlassCalReply.type)
}

// string description = 3;
inline void GlassCalReply::clear_description() {
  description_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& GlassCalReply::description() const {
  // @@protoc_insertion_point(field_get:Xproject.GlassCalReply.description)
  return _internal_description();
}
inline void GlassCalReply::set_description(const std::string& value) {
  _internal_set_description(value);
  // @@protoc_insertion_point(field_set:Xproject.GlassCalReply.description)
}
inline std::string* GlassCalReply::mutable_description() {
  // @@protoc_insertion_point(field_mutable:Xproject.GlassCalReply.description)
  return _internal_mutable_description();
}
inline const std::string& GlassCalReply::_internal_description() const {
  return description_.GetNoArena();
}
inline void GlassCalReply::_internal_set_description(const std::string& value) {
  
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void GlassCalReply::set_description(std::string&& value) {
  
  description_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Xproject.GlassCalReply.description)
}
inline void GlassCalReply::set_description(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Xproject.GlassCalReply.description)
}
inline void GlassCalReply::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Xproject.GlassCalReply.description)
}
inline std::string* GlassCalReply::_internal_mutable_description() {
  
  return description_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* GlassCalReply::release_description() {
  // @@protoc_insertion_point(field_release:Xproject.GlassCalReply.description)
  
  return description_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void GlassCalReply::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:Xproject.GlassCalReply.description)
}

// -------------------------------------------------------------------

// GlassBookReply

// string result = 1;
inline void GlassBookReply::clear_result() {
  result_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& GlassBookReply::result() const {
  // @@protoc_insertion_point(field_get:Xproject.GlassBookReply.result)
  return _internal_result();
}
inline void GlassBookReply::set_result(const std::string& value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:Xproject.GlassBookReply.result)
}
inline std::string* GlassBookReply::mutable_result() {
  // @@protoc_insertion_point(field_mutable:Xproject.GlassBookReply.result)
  return _internal_mutable_result();
}
inline const std::string& GlassBookReply::_internal_result() const {
  return result_.GetNoArena();
}
inline void GlassBookReply::_internal_set_result(const std::string& value) {
  
  result_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void GlassBookReply::set_result(std::string&& value) {
  
  result_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Xproject.GlassBookReply.result)
}
inline void GlassBookReply::set_result(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  result_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Xproject.GlassBookReply.result)
}
inline void GlassBookReply::set_result(const char* value, size_t size) {
  
  result_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Xproject.GlassBookReply.result)
}
inline std::string* GlassBookReply::_internal_mutable_result() {
  
  return result_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* GlassBookReply::release_result() {
  // @@protoc_insertion_point(field_release:Xproject.GlassBookReply.result)
  
  return result_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void GlassBookReply::set_allocated_result(std::string* result) {
  if (result != nullptr) {
    
  } else {
    
  }
  result_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), result);
  // @@protoc_insertion_point(field_set_allocated:Xproject.GlassBookReply.result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Xproject

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Xproject::GlassRequest_GlassMaterial> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Xproject::GlassRequest_GlassMaterial>() {
  return ::Xproject::GlassRequest_GlassMaterial_descriptor();
}
template <> struct is_proto_enum< ::Xproject::grpc_GlassType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Xproject::grpc_GlassType>() {
  return ::Xproject::grpc_GlassType_descriptor();
}
template <> struct is_proto_enum< ::Xproject::grpc_eOneGlassPanelResultType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Xproject::grpc_eOneGlassPanelResultType>() {
  return ::Xproject::grpc_eOneGlassPanelResultType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_grpc_5fglass_2eproto
