// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: grpc_glass.proto

#include "grpc_glass.pb.h"
#include "grpc_glass.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace Xproject {

static const char* grpc_Glass_method_names[] = {
  "/Xproject.grpc_Glass/Calculate",
};

std::unique_ptr< grpc_Glass::Stub> grpc_Glass::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< grpc_Glass::Stub> stub(new grpc_Glass::Stub(channel));
  return stub;
}

grpc_Glass::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Calculate_(grpc_Glass_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status grpc_Glass::Stub::Calculate(::grpc::ClientContext* context, const ::Xproject::GlassRequest& request, ::Xproject::GlassCalReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Calculate_, context, request, response);
}

void grpc_Glass::Stub::experimental_async::Calculate(::grpc::ClientContext* context, const ::Xproject::GlassRequest* request, ::Xproject::GlassCalReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Calculate_, context, request, response, std::move(f));
}

void grpc_Glass::Stub::experimental_async::Calculate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Xproject::GlassCalReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Calculate_, context, request, response, std::move(f));
}

void grpc_Glass::Stub::experimental_async::Calculate(::grpc::ClientContext* context, const ::Xproject::GlassRequest* request, ::Xproject::GlassCalReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Calculate_, context, request, response, reactor);
}

void grpc_Glass::Stub::experimental_async::Calculate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Xproject::GlassCalReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Calculate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Xproject::GlassCalReply>* grpc_Glass::Stub::AsyncCalculateRaw(::grpc::ClientContext* context, const ::Xproject::GlassRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Xproject::GlassCalReply>::Create(channel_.get(), cq, rpcmethod_Calculate_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Xproject::GlassCalReply>* grpc_Glass::Stub::PrepareAsyncCalculateRaw(::grpc::ClientContext* context, const ::Xproject::GlassRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Xproject::GlassCalReply>::Create(channel_.get(), cq, rpcmethod_Calculate_, context, request, false);
}

grpc_Glass::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      grpc_Glass_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< grpc_Glass::Service, ::Xproject::GlassRequest, ::Xproject::GlassCalReply>(
          std::mem_fn(&grpc_Glass::Service::Calculate), this)));
}

grpc_Glass::Service::~Service() {
}

::grpc::Status grpc_Glass::Service::Calculate(::grpc::ServerContext* context, const ::Xproject::GlassRequest* request, ::Xproject::GlassCalReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Xproject

